### ISSUE TITLE
Webengage dialogue accessibility issues.

### ISSUE THREAD

**Issue by neoeno** [moneyadviceservice/frontend#783]
We've had a report back from the DAC on the Savings Calculator. They included the following section regarding the feedback form, which I include below:

![screenshot 2014-11-13 16 30 51](https://cloud.githubusercontent.com/assets/1007202/5032007/79b73e38-6b52-11e4-9538-2dbd33c98b41.png)

> The icon to close the questionnaire is very small. This means that someone with mobility issues would not be able to select it due to the very small actionable area.

Happy to make the changes if anyone can point me to the right area. Equally happy for someone else to do it :stuck_out_tongue_winking_eye:

**Comment by seane** [comment]
No longer relevant, we don't use WebEngage any longer...
